//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DULIEU
    {
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string CMND { get; set; }
        public string SDT { get; set; }
        public string GioiTinh { get; set; }
        public string TenPhong { get; set; }
        public string QuocTich { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public Nullable<int> TongGiaDV { get; set; }
        public Nullable<int> TongGiaPhong { get; set; }
        public Nullable<int> TongGiaHD { get; set; }
    }
}
