//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGTHUE
    {
        public string MaDK { get; set; }
        public string MaKH { get; set; }
        public string TenPhong { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual THONGTIN_PHONG THONGTIN_PHONG { get; set; }
    }
}
