//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTIN_PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGTIN_PHONG()
        {
            this.PHONGTHUEs = new HashSet<PHONGTHUE>();
        }
    
        public string TenPhong { get; set; }
        public string LoaiPhong { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual KIEUPHONG KIEUPHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONGTHUE> PHONGTHUEs { get; set; }
    }
}
